baseURL = "https://www.pubhub.org.uk"
languageCode = "en-uk"
title = "PubHub"
author = "Steve Tuck"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
Paginate = 12
copyright = "PubHub"

theme = "github.com/theNewDynamic/gohugo-theme-ananke"

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "Home"
    url = "/"

[params]
  #facebook
  #twitter
  #linkedin
  #github
  #stackoverflow
  featured_image = "/beer-2166004_1920.jpg"
  favicon = "/favicon.ico"
  description = "Because saving money is thirsty work"
  background_color_class = "bg-black"

